#!/usr/bin/env node

/**
 * render-xslt.mjs
 *
 * End-to-end rendering: uses the XSLT stylesheet generated by odd-to-xslt.mjs
 * to transform TEI XML into HTML — powered by SaxonJS (xslt3 CLI).
 *
 * Pipeline:
 *   1. odd-to-xslt.mjs  → edition.xsl     (ODD → XSLT, build-time)
 *   2. render-xslt.mjs   → rendered HTML   (this script, XSLT → HTML)
 *
 * Multiple inputs: --tei accepts a single file, a directory (every *.xml
 * inside), a glob (e.g. "corpus/*.xml"), a comma-separated list, or a repeated
 * --tei flag. With one input the output is output/rendered-xslt.html (as
 * before); with several, one <basename>.html page is written per source plus an
 * index.html linking them. The XSLT engine is selected once and reused for the
 * whole corpus.
 *
 * Usage:
 *   node render-xslt.mjs --xsl <path> --tei <path|dir|glob> [--out <dir>]
 *
 * Primary engine: xslt3 CLI (SaxonJS)   — npm install xslt3
 * Fallback:       xslt-processor (pure JS XSLT 1.0)
 *
 * Outputs:
 *   <output-dir>/rendered-xslt.html             (single input)
 *   <output-dir>/<basename>.html + index.html   (multiple inputs)
 */

import { execSync } from "child_process";
import {
  readFileSync, mkdirSync, copyFileSync, rmSync,
} from "fs";
import { resolve, join } from "path";
import { tmpdir } from "os";
import { parseXmlToXast, extractTeiTitle } from "./odd-parser.mjs";
import {
  parseArgs, createLogger, writeOut,
  resolveInputFiles, htmlPageName, buildIndexPage,
} from "./cli.mjs";

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------
const cli = parseArgs();
const log = createLogger("render-xslt");

const xslPath = cli.get("--xsl") || "output/edition.xsl";
const teiArg  = cli.getAll("--tei");
const outDir  = cli.get("--out") || "output";

const teiFiles = resolveInputFiles(teiArg.length ? teiArg : "../examples/simler-poem.xml");
const multi = teiFiles.length > 1;

log(`XSLT stylesheet: ${xslPath}`);
log(`TEI source(s):    ${teiFiles.join(", ")}`);

const xslSrc = readFileSync(resolve(xslPath), "utf-8");

// ---------------------------------------------------------------------------
// Engine setup. The # character in workspace paths breaks shell invocations,
// so SaxonJS runs inside a temp directory holding edition.xsl; each document is
// written there as source.xml in turn.
// ---------------------------------------------------------------------------
const tempDir = join(tmpdir(), `odd-xslt-render-${Date.now()}`);
mkdirSync(tempDir, { recursive: true });
copyFileSync(resolve(xslPath), join(tempDir, "edition.xsl"));

/** SaxonJS via the xslt3 CLI (production-grade, XSLT 3.0). */
function saxonTransform(teiFile) {
  copyFileSync(resolve(teiFile), join(tempDir, "source.xml"));
  execSync(
    `npx --yes xslt3 -xsl:edition.xsl -s:source.xml -o:result.html`,
    { cwd: tempDir, stdio: ["pipe", "pipe", "pipe"], timeout: 120_000 },
  );
  return readFileSync(join(tempDir, "result.html"), "utf-8");
}

/** xslt-processor (lightweight pure-JS XSLT 1.0) — loaded and parsed lazily. */
let xsltProcess, xmlParse, xslDoc;
async function xpTransform(teiFile) {
  if (!xsltProcess) {
    ({ xsltProcess, xmlParse } = await import("xslt-processor"));
    xslDoc = xmlParse(xslSrc);
  }
  const xmlDoc = xmlParse(readFileSync(resolve(teiFile), "utf-8"));
  return xsltProcess(xmlDoc, xslDoc);
}

// On the first document, probe SaxonJS then xslt-processor; reuse whichever
// works for the rest of the corpus. Returns null only if neither is available.
let engine = null;
async function transform(teiFile) {
  if (engine === "saxon") return saxonTransform(teiFile);
  if (engine === "xslt-processor") return await xpTransform(teiFile);

  try {
    log(`Trying SaxonJS (xslt3 CLI)…`);
    const html = saxonTransform(teiFile);
    engine = "saxon";
    log(`✓ SaxonJS transformation succeeded — using it for the corpus`);
    return html;
  } catch (e) {
    log(`⚠ xslt3 not available (${e.message?.split("\n")[0]})`);
  }
  try {
    log(`Trying xslt-processor (pure-JS fallback)…`);
    const html = await xpTransform(teiFile);
    engine = "xslt-processor";
    log(`✓ xslt-processor transformation succeeded — using it for the corpus`);
    return html;
  } catch (e) {
    log(`⚠ xslt-processor not available (${e.message?.split("\n")[0]})`);
  }
  return null;
}

// ---------------------------------------------------------------------------
// Render each input. If no engine is available, fail loudly rather than fake
// the transformation with a hand-written fallback — only output derived from
// edition.xsl is a faithful render of the ODD.
// ---------------------------------------------------------------------------
const indexEntries = [];
for (const teiFile of teiFiles) {
  const html = await transform(teiFile);
  if (html == null) {
    console.error(
      `[render-xslt] ✗ No XSLT engine available - cannot render ${xslPath}.\n` +
      `  This renderer deliberately has no hand-written fallback: its output must\n` +
      `  come from the generated edition.xsl, not a parallel mapping. Install one of:\n` +
      `    - SaxonJS / xslt3 (XSLT 3.0):  npm install --no-save xslt3\n` +
      `    - xslt-processor (XSLT 1.0):   npm install --no-save xslt-processor\n` +
      `  (The default run uses 'npx xslt3' when network access is available.)`
    );
    try { rmSync(tempDir, { recursive: true }); } catch { /* ignore */ }
    process.exit(1);
  }

  const pageName = multi ? htmlPageName(teiFile) : "rendered-xslt.html";
  const outFile = writeOut(outDir, pageName, html);
  log(`✓ ${teiFile} → ${outFile}`);
  const title = extractTeiTitle(parseXmlToXast(readFileSync(resolve(teiFile), "utf-8")));
  indexEntries.push({ href: pageName, title: title || pageName, meta: `XSLT (${engine})` });
}

if (multi) {
  const indexFile = writeOut(outDir, "index.html", buildIndexPage({
    title: "TEI Edition — XSLT",
    subtitle: `${teiFiles.length} documents · generated stylesheet, server-free`,
    entries: indexEntries,
  }));
  log(`✓ Index written to ${indexFile}`);
}

// ---------------------------------------------------------------------------
// Cleanup
// ---------------------------------------------------------------------------
try { rmSync(tempDir, { recursive: true }); } catch { /* ignore */ }
log(`  Open in browser to view the rendered edition`);
